In [4]:
import numpy as np
n = [5, 10, 15, 20, 25]
x = np.array(n)
type(x)

numpy.ndarray

In [4]:
x.ndim

1

In [5]:
x.shape

(5,)

In [6]:
x.size

5

    #### task 2
   

In [8]:
n = [[-1, -2, -3, -4], [-2,-4, -6, -8]]
y = np.array(n)
y

array([[-1, -2, -3, -4],
       [-2, -4, -6, -8]])

In [12]:
type(y)

numpy.ndarray

In [14]:
print(y.ndim, y.shape, y.size, y.dtype, y.itemsize)

2 (2, 4) 8 int32 4


In [15]:
y = np.full(shape=(2,3), fill_value="me")
print(y)

[['me' 'me' 'me']
 ['me' 'me' 'me']]


In [20]:
x2 = np.full(shape=(3,2,2), fill_value=1)
x2

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [24]:
x3 = np.eye(4)
x3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.seed(100)
x4 = np.random.rand(3,4,2)
x4

array([[[0.54340494, 0.27836939],
        [0.42451759, 0.84477613],
        [0.00471886, 0.12156912],
        [0.67074908, 0.82585276]],

       [[0.13670659, 0.57509333],
        [0.89132195, 0.20920212],
        [0.18532822, 0.10837689],
        [0.21969749, 0.97862378]],

       [[0.81168315, 0.17194101],
        [0.81622475, 0.27407375],
        [0.43170418, 0.94002982],
        [0.81764938, 0.33611195]]])

In [39]:
np.random.seed(100)
x5 = 5 + 2.5* np.random.randn(20)
print(x5.mean(), x5.std())

4.9907991127984985 1.916209866367152


In [41]:
x6 = np.arange(2, 41, 2)
x6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [42]:
x7 = np.linspace(10, 20 , 30)
x7

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])

In [46]:
import numpy as np
x = np.arange(30).reshape(6, 5)
res = np.vsplit(x, 2)
print(res[0], end='\n\n')

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])]

In [53]:
x = np.arange(10).reshape(2,5)
res1 = np.hsplit(x, (2,4))
print(res1[0], end='\n\n')
print(res1[1], end='\n\n')
print(res1[2])

[[0 1]
 [5 6]]

[[2 3]
 [7 8]]

[[4]
 [9]]


In [60]:
import numpy as np

x = np.arange(90).reshape(3, 15, 2)
x.size

90

In [66]:
x = np.arange(20)
x.shape
y = x.reshape(2,10)
np.hsplit(y, 2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]]), array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]])]

In [68]:
z = x.reshape(4,5)
np.vsplit(z, 2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [73]:
p = np.array([3, 6, 9, 12]).reshape(2,2)
q = np.array([15, 18, 21, 24, 27, 30]).reshape(2,3)
s = np.hstack((p,q))
s

array([[ 3,  6, 15, 18, 21],
       [ 9, 12, 24, 27, 30]])

In [74]:
x = np.arange(4).reshape(2,2)
print(x.tolist())

[[0, 1], [2, 3]]


In [77]:
x = np.arange(1,7).reshape(2,3)
x **2 + 5

array([[ 6,  9, 14],
       [21, 30, 41]], dtype=int32)

In [82]:
x = np.linspace(-30,30, 30).reshape(5,6)
print(x.sum(axis=0), x.sum(axis=1), end='\n\n')

[-25.86206897 -15.51724138  -5.17241379   5.17241379  15.51724138
  25.86206897] [-1.48965517e+02 -7.44827586e+01  1.42108547e-14  7.44827586e+01
  1.48965517e+02]



In [89]:
x = 10 +(2* np.random.randn(50))
print(x.mean(), x.std(), x.var())

10.002195236085399 1.9765279001302805 3.906662539993416


In [100]:
y = np.array([[0, 1, 2],
              [3, 4, 5]])
print(y[1:3]) 

[[3 4 5]]


In [103]:
import numpy as np

x = np.arange(30).reshape(3,5,2)
print(x[1][::2][1])

[14 15]


In [112]:
x = np.arange(30).reshape(3,5,2)
print(x[-1, 2:-1, -1])

[25 27]


In [113]:
x = np.array([[0, 1], [1, 1], [2, 2]])
print(x.sum(-1))

[1 2 4]


In [118]:
x = np.arange(30).reshape(3,5,2)
print(x[-1, 2:-1, -1])

[25 27]


In [117]:
x = np.arange(4).reshape(2,2)
print(np.isfinite(x))

[[ True  True]
 [ True  True]]


In [121]:
x = np.arange(12).reshape(3,4)
print(x[:,1])

[1 5 9]


In [123]:
x = np.arange(4).reshape(2,2)
print(np.isfinite(x))

[[ True  True]
 [ True  True]]


In [7]:
import numpy as np
a = np.arange(12).reshape((4,3))
b = np.arange(4).reshape(4,1)
print(a*b)

[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]
 [27 30 33]]


In [16]:
x = np.arange(30).reshape((2, 3, 5))
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [18]:
b = np.array([True, False])
x[b]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [19]:
x[b,:,1:3]

array([[[ 1,  2],
        [ 6,  7],
        [11, 12]]])

In [13]:
x[:,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18],
       [21, 22, 23],
       [26, 27, 28]])

In [15]:
x[:2,2:]

array([[2, 3, 4],
       [7, 8, 9]])